---
- name: First Setup | Update the package list
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: First Setup | Upgrade a server with apt
  apt:
    upgrade: dist
  register: upgrade
- name: First Setup | Change root password 
  user:
    user: root 
    update_password: always 
    password: "{{ new_root_password }}" 
- name: First Setup | Create new user 
  user:
    user: "{{ new_user }}" 
    password: "{{ new_user_password }}" 
    groups: sudo   # Empty by default.
    shell: /bin/bash
- name: First Setup | Copy ssh id
  authorized_key:
    user: "{{ new_user }}" 
    key: "{{ item }}"
    manage_dir: no
  with_file:
    - "{{ ssh_key }}"
- name: First Setup | Modify sshd file config 
  template:
    src: sshd_config.j2
    dest: "/etc/ssh/sshd_config"
    mode: 0644
- name: First Setup | Generate missing host keys
  command: ssh-keygen -A
- name: First Setup | Restart ssh
  service:
    name: ssh
    state: restarted
# TODO:
# Modify iptables
# Install iptables-persistent
