---
- name: OpenVPN | sysctl | Enable IPv4 traffic forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"

- name: OpenVPN | Configuration | Copy OpenVPN server configuration files into place
  template:
    src: etc_openvpn_server.conf.j2
    dest: "{{ openvpn_path }}/{{ item.proto }}-{{ item.port }}.conf"
  with_items: "{{ openvpn_instances }}"
  notify:
    - start openvpn

- name: OpenVPN | systemd | Enable services
  service:
    name: "openvpn@{{ item.proto }}-{{ item.port }}.service"
    enabled: true
  with_items: "{{ openvpn_instances }}"
  notify:
    - start openvpn
